<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5er7S3\Tests_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5er7S3/Tests_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5er7S3.legacy');

    return;
}

if (!\class_exists(Tests_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQ5er7S3\Tests_AppKernelTestDebugContainer::class, Tests_AppKernelTestDebugContainer::class, false);
}

return new \ContainerQ5er7S3\Tests_AppKernelTestDebugContainer([
    'container.build_hash' => 'Q5er7S3',
    'container.build_id' => 'b056b1c5',
    'container.build_time' => 1654512379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5er7S3');
