<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUk6jg0n\Tests_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUk6jg0n/Tests_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUk6jg0n.legacy');

    return;
}

if (!\class_exists(Tests_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUk6jg0n\Tests_AppKernelTestDebugContainer::class, Tests_AppKernelTestDebugContainer::class, false);
}

return new \ContainerUk6jg0n\Tests_AppKernelTestDebugContainer([
    'container.build_hash' => 'Uk6jg0n',
    'container.build_id' => 'e24db713',
    'container.build_time' => 1639100623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUk6jg0n');
