services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  BarthyKoeln\BrowserslistCheckBundle\Twig\BrowserslistCheckExtension:
    public: true
    tags: ['twig.extension']

  BarthyKoeln\BrowserslistCheckBundle\Service\BrowserslistCheck:
    public: true
