<?php

namespace ContainerUk6jg0n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrowserslistCheckExtensionService extends Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'BarthyKoeln\BrowserslistCheckBundle\Twig\BrowserslistCheckExtension' shared autowired service.
     *
     * @return \BarthyKoeln\BrowserslistCheckBundle\Twig\BrowserslistCheckExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 5).'/src/Twig/BrowserslistCheckExtension.php';

        return $container->services['BarthyKoeln\\BrowserslistCheckBundle\\Twig\\BrowserslistCheckExtension'] = new \BarthyKoeln\BrowserslistCheckBundle\Twig\BrowserslistCheckExtension(($container->services['BarthyKoeln\\BrowserslistCheckBundle\\Service\\BrowserslistCheck'] ?? $container->load('getBrowserslistCheckService')));
    }
}
