<?php

namespace ContainerUk6jg0n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrowserslistCheckService extends Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'BarthyKoeln\BrowserslistCheckBundle\Service\BrowserslistCheck' shared autowired service.
     *
     * @return \BarthyKoeln\BrowserslistCheckBundle\Service\BrowserslistCheck
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Service/BrowserslistCheck.php';

        return $container->services['BarthyKoeln\\BrowserslistCheckBundle\\Service\\BrowserslistCheck'] = new \BarthyKoeln\BrowserslistCheckBundle\Service\BrowserslistCheck(['Chrome' => 94.0, 'Firefox' => 93.0, 'Safari' => 14.0, 'Opera' => 79.0, 'Edge' => 94.0, 'iOS' => 14.0, 'Samsung' => 15.0, 'ChromeAndroid' => 94.0], ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
