<?php

namespace ContainerUk6jg0n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession_Storage_MockFileService extends Tests_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'session.storage.mock_file' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage
     *
     * @deprecated Since symfony/framework-bundle 5.3: The "session.storage.mock_file" service is deprecated, use "session.storage.factory.mock_file" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/framework-bundle', '5.3', 'The "session.storage.mock_file" service is deprecated, use "session.storage.factory.mock_file" instead.');

        return $container->privates['session.storage.mock_file'] = new \Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage(($container->targetDir.''.'/sessions'), 'MOCKSESSID', ($container->privates['session.storage.metadata_bag'] ?? $container->load('getSession_Storage_MetadataBagService')));
    }
}
